// Generated by CoffeeScript 1.7.1
(function() {
  var CSS_STR, IFRAME_URL, Tok3n, el, getOrigin, head, iframe, script, stylesheet, tagDefaults;

  IFRAME_URL = "http://localhost:5000/login-v2";

  CSS_STR = "#tok3n-iframe {\n  overflow: hidden;\n  opacity: 0;\n  position: fixed;\n  top: 0;\n  left: 0;\n  height: 0;\n  width: " + document.documentElement.clientWidth + "px;\n  width: 100vw;\n  border: none;\n  z-index: 9999;\n} \n#tok3n-iframe.visible {\n  height: " + document.documentElement.clientHeight + "px;\n  height: 100vh;\n  opacity: 1;\n}";

  tagDefaults = {
    name: "button",
    innerHtml: "Authenticate with Tok3n",
    className: "tok3n-authenticate-button",
    id: "tok3n-authenticate-button"
  };

  head = document.head || document.getElementsByTagName("head")[0];

  stylesheet = document.createElement("style");

  stylesheet.type = "text/css";

  stylesheet.appendChild(document.createTextNode(CSS_STR));

  head.appendChild(stylesheet);

  iframe = document.createElement("iframe");

  iframe.src = IFRAME_URL;

  iframe.id = "tok3n-iframe";

  iframe.setAttribute("allowtransparency", true);

  document.body.appendChild(iframe);

  getOrigin = function(iframe) {
    return (new URL(iframe.src)).origin;
  };

  this.Tok3n = Tok3n = (function(iframe) {
    var messageHandler, origin, postMessage, pub;
    origin = getOrigin(iframe);
    postMessage = function(msg) {
      msg.parentOrigin = window.location.origin;
      return iframe.contentWindow.postMessage(msg, origin);
    };
    messageHandler = function(message) {
      switch (message.type) {
        case "hideComplete":
          return iframe.classList.remove("visible");
      }
    };
    window.addEventListener("message", function(event) {
      if (event.origin === origin) {
        return messageHandler(event.data);
      }
    });
    pub = {
      showIFrame: function() {
        postMessage({
          cmd: "show"
        });
        return iframe.classList.add("visible");
      },
      hideIFrame: function() {
        return postMessage({
          cmd: "hide"
        });
      }
    };
    return pub;
  })(iframe);

  script = document.querySelector("script[data-tok3n-integration]");

  if (script.hasAttribute("data-render-tag")) {
    el = document.createElement(script.dataset.tagName || tagDefaults.name);
    el.innerHTML = script.dataset.tagInnerHtml || tagDefaults.innerHtml;
    el.id = script.dataset.tagId || tagDefaults.id;
    el.className = script.dataset.tagClassName || tagDefaults.className;
    if (el.tagName.toLowerCase() === "a") {
      el.href = "javascript:void(0)";
    }
    el.addEventListener("click", Tok3n.showIFrame);
    script.parentElement.insertBefore(el, script);
  }

}).call(this);
