// Generated by CoffeeScript 1.7.1
(function() {
  var CSS_STR, IFRAME_URL, Tok3n, el, head, iframe, iframeOrigin, script, stylesheet, tagDefaults, tok3nElement;
  var response;

  //IFRAME_URL = "http://localhost:5000/iframe";
  //IFRAME_URL = "http://localhost:8080/api_v2_iframe/iframe-template.html";
  IFRAME_URL = "http://secure.tok3n.com/api_v2_iframe/iframe-template.html";

  CSS_STR = "#tok3n-iframe {\n  overflow: hidden;\n  opacity: 0;\n  position: fixed;\n  top: 0;\n  left: 0;\n  height: 0;\n  width: " + document.documentElement.clientWidth + "px;\n  width: 100vw;\n  border: none;\n  z-index: 9999;\n} \n#tok3n-iframe.visible {\n  height: " + document.documentElement.clientHeight + "px;\n  height: 100vh;\n  opacity: 1;\n}";

  tagDefaults = {
    name: "button",
    innerHtml: "Authenticate with Tok3n",
    className: "tok3n-authenticate",
    id: "tok3n-authenticate"
  };

  head = document.head || document.getElementsByTagName("head")[0];

  stylesheet = document.createElement("style");

  stylesheet.type = "text/css";

  stylesheet.appendChild(document.createTextNode(CSS_STR));

  head.appendChild(stylesheet);

  iframe = document.createElement("iframe");

  iframe.src = IFRAME_URL;

  iframe.id = "tok3n-iframe";

  iframe.setAttribute("allowtransparency", true);

  document.body.appendChild(iframe);

  iframeOrigin = (new URL(iframe.src)).origin;

  this.Tok3n = Tok3n = (function() {
    var messageHandler, postMessage;
    postMessage = function(msg) {
      msg.parentOrigin = window.location.origin;
      return iframe.contentWindow.postMessage(msg, iframeOrigin);
    };
    messageHandler = function(message) {
      switch (message.type) {
        case "hideComplete":
          console.log(message);
          if (message.detail){
            var ev = new CustomEvent("response",message);
            script.dispatchEvent(ev);
          }
          return iframe.classList.remove("visible");
        case "showComplete":
          return iframe.classList.add("visible");
      }
    };
    iframe.addEventListener("load", function(event) {
      return window.addEventListener("message", function(event) {
        if (event.origin === iframeOrigin) {
          return messageHandler(event.data);
        }
      }, false);
    }, false);
    return {
      showIFrame: function(trgt,apikey,userKey) {
        postMessage({
          cmd: "show",
          target: trgt,
          publickey: apikey,
          userkey: userKey
        });
        iframe.classList.add("visible");
        return iframe.focus();
      },
      hideIFrame: function() {
        return postMessage({
          cmd: "hide"
        });
      }
    };
  })();

  script = document.querySelector("script[data-tok3n-integration]");

  if (script) {
    var action = script.getAttribute("action");
    if (!action){
      action = "authorize";
    }
    var publickey = script.getAttribute("public-key");
    var userkey  = script.getAttribute("user-key");

    el = document.createElement(script.dataset.tagName || tagDefaults.name);
    el.innerHTML = script.dataset.tagInnerHtml || tagDefaults.innerHtml;
    el.id = script.dataset.tagId || tagDefaults.id;
    el.className = script.dataset.tagClassName || tagDefaults.className;
    if (el.tagName.toLowerCase() === "a") {
      el.href = "javascript:void(0)";
    }
    el.addEventListener("click", function() {
      console.log(Tok3n);
      return Tok3n.showIFrame(action,publickey,userkey);
    });
    script.parentElement.insertBefore(el, script);
    tok3nElement = el;
  }

}).call(this);
